M48
; DRILL file {KiCad 9.0.3} date 2025-09-02T14:59:49-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-02T14:59:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X87.95Y-28.621
T2
X50.175Y-59.329
X50.626Y-50.74
T1
G00X95.0Y-28.621
M15
G01X95.3Y-28.621
M16
G05
M30
