M48
; DRILL file {KiCad 9.0.6-rc2} date 2026-03-07T14:25:29-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-07T14:25:29-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-rc2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X87.95Y-28.621
T2
X50.175Y-59.329
X50.626Y-50.74
T1
G00X95.0Y-28.621
M15
G01X95.3Y-28.621
M16
G05
M30
