M48
; DRILL file {KiCad 7.0.6} date Tue Mar 26 19:33:24 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-26T19:33:24-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X8.4551Y-3.4962
X8.7484Y-3.4962
T2
X6.9728Y-4.759
X6.9905Y-4.4209
T0
M30
