M48
; DRILL file {KiCad 7.0.6} date Fri Dec 15 21:48:46 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-15T21:48:46-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X6.3162Y-5.5751
X6.5438Y-5.5751
T2
X6.9728Y-4.759
X6.9905Y-4.4209
T0
M30
